### ISSUE TITLE
Include a view in the landscape page using the dates

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#139] opened 2020-03-14 15:18 UTC
It would be nice in the Landscape page to display a diagram that shows the evolution of the number of ontologies in AgroPortal thru time (since 2015). 
Maybe a combined view that will also include new submissions. 

Plus some statistics on the number of update of ontologies... something to show how AgroPortal is alive.

**Comment by syphax-bouazzouni** [comment] 2023-11-10 11:30
Duplicate of https://github.com/agroportal/project-management/issues/333

**Closed as completed by syphax-bouazzouni** 2023-11-10 11:30 UTC
