### ISSUE TITLE
Fail in automatic pull for AgroPortal ontologies "connected" to NCBO BioPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#172] opened 2022-01-06 11:17 UTC
We have notification (everyday) of automatic pull failure of 5/6 ontologies in AgroPortal that are connected to BioPortal. 
Connected = which AgroPortal's pullLocation is a URL in BioPortal e.g. 
For XEO we have the following pullLocation
https://data.bioontology.org/ontologies/XEO/download?apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e 

We have 6 ontologies concerned: 
XEO, PECO (connected to EO), LBO, SNPO, BT, STY
All pullLocation URLs works in the browser but 5 ontologies (all but STY) generate error 
https://github.com/ontoportal-lirmm/ncbo_cron/blob/master/lib/ncbo_cron/ontology_pull.rb#L82

**Comment by jonquet** [comment] 2022-01-06 11:32
Checking the logs
/srv/ontoportal/ncbo_cron/logs/scheduler-pull.log

We can see the failure during the `remote_file_exists?` test
https://github.com/ontoportal-lirmm/ncbo_cron/blob/master/lib/ncbo_cron/ontology_pull.rb#L54

**Comment by syphax-bouazzouni** [comment] 2022-01-06 14:36
More details about this issue.

## Context
There is an exemple in the scheduler-pull.log file of an exception that this ontologies generate
![image](https://user-images.githubusercontent.com/29259906/148397357-6dfd1c40-69e7-4816-bc17-f6bf805e4374.png)

The **RemoteFileException** is raised by this function [ontology_pull](https://github.com/ontoportal-lirmm/ncbo_cron/blob/master/lib/ncbo_cron/ontology_pull.rb#L80), when [remote_file_exists?](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L2330) test fails

## Result

The **RemoteFileException** is raised when we can't acces a to a pullLocation url (the response header >= 400 for http requests)
The problem is that **the 6 ontologies concerned have reachable pullLocation url**  , so why do we have this **RemoteFileException** exception ?
## Solutions

1. Update CA certifications : https://blog.engineyard.com/ruby-ssl-error-certificate-verify-failed

**Comment by jonquet** [comment] 2022-01-06 17:46
I think the function [check_http_file(url)](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L2363) might have an issue with the apikey URL parameter => the file is not accessible then not retrieved.

The code 
`response_valid = http.head(url.request_uri).code.to_i < 400` seems to check the path of the URL only and ignore the query part... 

Cf : https://apidock.com/ruby/URI/HTTP/request_uri
Maybe we need a line of code earlier in the function to build a proper URL from the given url parameter then request_uri will be the good, complete URL.

**Comment by jonquet** [comment] 2022-01-10 14:53
@syphax-bouazzouni  To report here the fix (with certificates) tested last friday.

**Comment by jonquet** [comment] 2022-01-10 14:54
Seems (from log Jan 8th) that previous fix (with new certificates) has not mitigated the issue.

**Comment by syphax-bouazzouni** [comment] 2022-01-11 14:53
see applied solutions in my previous response, this comment is its report.
## Fix report
**It's seems it worked**, proves are those captures of the ncbo scheduler-pull log of yesterday (10th January), where we can see that **the RemoteFileException is no more there** (see Context section of my last response).
### For XEO
![image](https://user-images.githubusercontent.com/29259906/148962874-aa582d34-19f7-415e-8ead-102a20c90211.png)

### For PECO
![image](https://user-images.githubusercontent.com/29259906/148963616-e38dc6d4-97c4-4281-8744-1a7bca6350cc.png)

### For LBO ( it was updated successfully and a new submission was created) 
![image](https://user-images.githubusercontent.com/29259906/148964252-7c053598-564a-421d-8ea3-21a16f834706.png)

### For SNPO
![image](https://user-images.githubusercontent.com/29259906/148965143-0c1ac447-d387-4b6d-a5f9-c49575685650.png)

### For BT
![image](https://user-images.githubusercontent.com/29259906/148965429-fc073877-c234-41c2-8d40-b6c25712dd7e.png)

**Comment by jonquet** [comment] 2022-01-11 15:14
Indeed. It worked and LBO has been updated (I have manually corrected the version number). The fix in the cron was not necessarily active on Jan 8th the, I believe. 

Now we only need to understand what's going on with STY.

**Comment by syphax-bouazzouni** [comment] 2022-01-11 15:15
i don't think the STO special case , was resolved (the STO acronym don't appear in this last logs)

Please @jonquet, make a separated issue (if you didn't yet resolved it) for the case of STO where you explain it's specificity (UMLS for exemple i think).

I let you also the hand to close this one, if it suit you.

**Comment by jonquet** [comment] 2022-01-11 16:31
Working on it. I don't see STY (it STY not STO )in the logs either. Which means that it's not an ontology "connected" pull issue but something else that exclude STY from the list of ontologies processed by the script.

**Closed as completed** 2022-01-11 16:31 UTC
Labels: content
