### ISSUE TITLE
Format dans adminstration des métadonnées genere une page vide

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#556] opened 2024-05-29 10:23 UTC
<img width="714" alt="Capture d’écran 2024-05-29 à 12 21 18" src="https://github.com/agroportal/project-management/assets/7379183/ecfa56df-bd84-4f30-9d0b-342dc3f721a9">

**Comment by jonquet** [comment] 2024-05-29 10:33
"Location" genere la meme erreeur

**Comment by syphax-bouazzouni** [comment] 2024-12-12 01:53
Duplicate of https://github.com/agroportal/project-management/issues/591

**Closed as completed by syphax-bouazzouni** 2024-12-12 01:53 UTC
