### ISSUE TITLE
Double descriptions for Scheme in AGROTERMOS

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#514] opened 2024-04-16 19:19 UTC
https://agroportal.lirmm.fr/ontologies/AGROTERMOS?p=schemes

<img width="491" alt="Capture d’écran 2024-04-16 à 21 17 26" src="https://github.com/agroportal/project-management/assets/7379183/ff616ac8-94d9-47c1-b9b1-693f5de714ad">

Where as the source file contains only one description. 
<img width="585" alt="Capture d’écran 2024-04-16 à 21 18 17" src="https://github.com/agroportal/project-management/assets/7379183/92cc649a-d631-4f2f-8b2f-b9a6caa7eb67">

I suspet this comes from dctterms/dc which map to the same thing in our system and create a duplicate.

**Comment by syphax-bouazzouni** [comment] 2024-04-22 05:29
The API returns a unique value for the description, so the issue is in the UI
https://data.agroportal.lirmm.fr/ontologies/AGROTERMOS/schemes/https%3A%2F%2Fsistemas.sede.embrapa.br%2Fagrotermos?display=all&display_links=false&display_context=false
![image](https://github.com/agroportal/project-management/assets/29259906/1ee89372-d0bc-4526-91ff-edb257d5f75b)

**Comment by syphax-bouazzouni** [comment] 2024-04-29 07:40
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/584

**Closed as completed by syphax-bouazzouni** 2024-04-29 07:40 UTC
Labels: enhancement, content
