### ISSUE TITLE
Fixing LOOM mappings duplicates

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#284] opened 2022-06-24 08:48 UTC
For long time we have weird non easy explainable LOOM mapping duplicates. 

For instance in CO_321 "Grain size"
http://agroportal.lirmm.fr/ontologies/CO_321/?p=classes&conceptid=https%3A%2F%2Fcropontology.org%2Frdf%2FCO_321%3A0000040&jump_to_nav=true#mappings

<img width="770" alt="image" src="https://user-images.githubusercontent.com/7379183/175499069-8c8c6066-8122-4d1f-821a-78e589214896.png">
Mapping sto TO and CO_324 are multiples without explanation.

The corresponding REST call does contains the duplicates too: 
http://data.agroportal.lirmm.fr/ontologies/CO_321/classes/https%3A%2F%2Fcropontology.org%2Frdf%2FCO_321%3A0000040/mappings?display_context=false&display_links=false

However, the mappings.ttl file in the repository folder does contains only one occurence of "grainsize"

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/7379183/175499393-b4a7d012-c859-4640-b605-291ece702acf.png">

**Comment by jonquet** [comment] 2022-06-24 09:21
An exact match search in AgroPortal does find the "same" ontologies that LOOM detect mapping too : TO, WHEATPHENOTYPE, AGRO, CO_324

<img width="945" alt="image" src="https://user-images.githubusercontent.com/7379183/175505602-e5ef0e02-f157-4641-8ff0-3a952f23a175.png">

But this does not explain the duplicates.

**Comment by syphax-bouazzouni** [comment] 2022-06-29 07:27
duplicate of https://github.com/agroportal/project-management/issues/133

**Comment by syphax-bouazzouni** [comment] 2024-07-08 02:58
Same issue as https://github.com/agroportal/project-management/issues/505, of zombie graphs. 
![image](https://github.com/agroportal/project-management/assets/29259906/92149bd8-56e5-4520-a718-8d652bcfdc91)

**Closed as completed by syphax-bouazzouni** 2024-07-08 02:58 UTC

**Comment by jonquet** [comment] 2024-07-09 08:02
Dude we were surrounded by zombies !
