### ISSUE TITLE
Faire nettoyage lié a CSOPRA 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#572] opened 2024-06-11 08:40 UTC
https://agroportal.lirmm.fr/ontologies/AGRO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAGRO_00000139&jump_to_nav=true

<img width="967" alt="Capture d’écran 2024-06-11 à 10 39 40" src="https://github.com/agroportal/project-management/assets/7379183/8511034c-ad9a-417a-8b4e-823c17305283">

**Comment by jonquet** [comment] 2024-06-11 08:41
Faut qu'on discute comme techniquement faire ce type de nettoyage qu'on puisse le faire ensute .. sans activité de developpement.

**Comment by syphax-bouazzouni** [comment] 2024-06-12 07:36
maybe will be fixed by just running 
```
bin/ncbo_ontology_mapping_counts -o CSOPRA
```

**Comment by syphax-bouazzouni** [comment] 2024-07-04 06:51
The cause of this is that we have a lot of zombie graphs of CSOPRA 
![image](https://github.com/agroportal/project-management/assets/29259906/05352fc1-6f47-4e08-8155-8f3d30f88292)

**Comment by jonquet** [comment] 2024-07-04 07:40
Pourquoi le script mapping count?

**Comment by syphax-bouazzouni** [comment] 2024-07-05 03:02
Fixed by removing the zombie graphs and running the mappings count script. 
![image](https://github.com/agroportal/project-management/assets/29259906/cf18fa8e-d0bc-4854-9969-4841eb0a8cea)

In addition, I created this issue https://github.com/agroportal/project-management/issues/586  to track the creation of an admin in the future to detect these Zobmie graphs 


> Pourquoi le script mapping count?

@jonquet je ne sais pas exactement ce que ce script fait, mais ici je l'utilise apres avoir suppirmer les graph zombies pour qui'il mette a jour le count des mappings entre ontologies pour ne pas prendre les mappings des graphs zombies.

**Closed as completed by syphax-bouazzouni** 2024-07-05 03:02 UTC
Labels: content
