### ISSUE TITLE
"PLACE" ontology administrator does not exist

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#208] opened 2022-02-10 12:40 UTC
## The ontology admin
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29259906/153410193-3224cf63-ee15-4010-86b2-12a07514bdef.png">

## User does not exist
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29259906/153410335-a0202f8a-e357-4fdf-baa8-690dbd525a4f.png">

**Comment by jonquet** [comment] 2022-02-10 14:27
esaie was a duplicate of esaieb

Problem should be fixed now: 
http://data.agroportal.lirmm.fr/ontologies/PLACE?display=administeredBy

**Closed as completed** 2022-02-14 09:57 UTC
Labels: content
